package ws.roomplanner;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-12-16T15:54:31.468+03:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://roomplanner/", name = "RoomPlannerService")
@XmlSeeAlso({ObjectFactory.class})
public interface RoomPlannerService {

    @WebResult(name = "plan", targetNamespace = "")
    @RequestWrapper(localName = "doPlan", targetNamespace = "http://roomplanner/", className = "ws.roomplanner.DoPlan")
    @WebMethod
    @ResponseWrapper(localName = "doPlanResponse", targetNamespace = "http://roomplanner/", className = "ws.roomplanner.DoPlanResponse")
    public ws.roomplanner.Plan doPlan(
        @WebParam(name = "roomList", targetNamespace = "")
        java.util.List<ws.roomplanner.Room> roomList,
        @WebParam(name = "roomCategoryList", targetNamespace = "")
        java.util.List<ws.roomplanner.RoomCategory> roomCategoryList,
        @WebParam(name = "reservationList", targetNamespace = "")
        java.util.List<ws.roomplanner.Reservation> reservationList,
        @WebParam(name = "roomAssignmentList", targetNamespace = "")
        java.util.List<ws.roomplanner.RoomAssignment> roomAssignmentList
    );
}
