package ws.roomplanner;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-11-06T15:30:48.647+04:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "RoomPlannerSoapServiceService", 
                  wsdlLocation = "src/java/roomPlanner.wsdl",
                  targetNamespace = "http://roomplanner/") 
public class RoomPlannerSoapServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://roomplanner/", "RoomPlannerSoapServiceService");
    public final static QName RoomPlannerSoapServicePort = new QName("http://roomplanner/", "RoomPlannerSoapServicePort");
    static {
        URL url = RoomPlannerSoapServiceService.class.getResource("src/java/roomPlanner.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RoomPlannerSoapServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/java/roomPlanner.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public RoomPlannerSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RoomPlannerSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoomPlannerSoapServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RoomPlannerSoapServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RoomPlannerSoapServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RoomPlannerSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RoomPlannerSoapService
     */
    @WebEndpoint(name = "RoomPlannerSoapServicePort")
    public RoomPlannerSoapService getRoomPlannerSoapServicePort() {
        return super.getPort(RoomPlannerSoapServicePort, RoomPlannerSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoomPlannerSoapService
     */
    @WebEndpoint(name = "RoomPlannerSoapServicePort")
    public RoomPlannerSoapService getRoomPlannerSoapServicePort(WebServiceFeature... features) {
        return super.getPort(RoomPlannerSoapServicePort, RoomPlannerSoapService.class, features);
    }

}
